name: 'Flutter Test Action'
description: 'Run Flutter tests'
runs:
  using: 'composite'
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: stable
        flutter-version: 3.27.1

    - name: Run Flutter Test
      run: |
        dart run localizely_sdk:generate
        flutter test
      shell: bash
